<a href="https://colab.research.google.com/github/DanielBarri/ejerciciosETL/blob/main/Problema1AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

In [31]:
#Paso 1: Subir datos a dataframe

print("Comenzando extracción......")

df = pd.read_csv("eic2025_simulada.csv")
print("Filas y columnas:", df.shape)

print("Finalizando extracción......")

Comenzando extracción......
Filas y columnas: (5000, 11)
Finalizando extracción......

In [33]:
df.head(10)

   folio                          entidad    sexo  edad tipo_localidad habla_lengua_indigena  escolaridad_anios  integrantes_hogar       condicion_actividad  ingreso_mensual afiliacion_salud
0      1                        Zacatecas   Mujer    26         Urbana                    No                9.0                  2                   Ocupada           3730.0               Sí
1      2                          Jalisco  Hombre    46         Urbana                    No                5.0                  4  No económicamente activa              0.0               No
2      3                           Sonora  Hombre    31         Urbana                    No               11.0                  3                   Ocupada           8670.0               Sí
3      4                           Sonora  Hombre    41         Urbana                    No                9.0                  4  No económicamente activa              0.0               Sí
4      5                          Yucatán  Hombre    74         Urbana                    Sí               11.0                  4                   Ocupada           7040.0               Sí
5      6                          Chiapas   Mujer    40         Urbana                    Sí               10.0                  3                   Ocupada           4840.0               Sí
6      7                         Guerrero   Mujer    57         Urbana                    No               13.0                  4                   Ocupada           7160.0               Sí
7      8  Veracruz de Ignacio de la Llave  Hombre    57          Rural                    No                8.0                  2                   Ocupada           2340.0               Sí
8      9                           Oaxaca   Mujer    82         Urbana                    Sí                6.0                  3                   Ocupada           3730.0               Sí
9     10                       Guanajuato   Mujer    45         Urbana                    No               10.0                  3                   Ocupada          13020.0               Sí

In [42]:
entradas = ["entidad", "sexo", "edad", "tipo_localidad", "habla_lengua_indigena", "escolaridad_anios", "integrantes_hogar", "condicion_actividad", "ingreso_mensual"]
salida = "afiliacion_salud"

x = df[entradas] #datos de entrada
y = df[salida]   #dato de salida
print("Entradas: ", x.shape,"| Salidas: ", y.shape )

Entradas:  (5000, 9) | Salidas:  (5000,)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   folio                  5000 non-null   int64
 1   entidad                5000 non-null   object
 2   sexo                   5000 non-null   object
 3   edad                   5000 non-null   int64
 4   tipo_localidad         5000 non-null   object
 5   habla_lengua_indigena  5000 non-null   object
 6   escolaridad_anios      4925 non-null   float64
 7   integrantes_hogar      5000 non-null   int64
 8   condicion_actividad    5000 non-null   object
 9   ingreso_mensual        4777 non-null   float64
 10  afiliacion_salud       5000 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 429.8+ KB

In [36]:
faltantes = df.isnull().sum()
pd.DataFrame({'faltantes': faltantes, 'porcentaje': (faltantes /len(df)*100).round(2)})

                       faltantes  porcentaje
folio                          0        0.00
entidad                        0        0.00
sexo                           0        0.00
edad                           0        0.00
tipo_localidad                 0        0.00
habla_lengua_indigena          0        0.00
escolaridad_anios             75        1.50
integrantes_hogar              0        0.00
condicion_actividad            0        0.00
ingreso_mensual              223        4.46
afiliacion_salud               0        0.00

In [37]:
df.describe().round(2)

         folio     edad  escolaridad_anios  integrantes_hogar  ingreso_mensual
count  5000.00  5000.00            4925.00            5000.00          4777.00
mean   2500.50    44.49               9.90               3.70          5467.34
std    1443.52    19.52               3.44               1.66          6421.45
min       1.00    15.00               0.00               1.00             0.00
25%    1250.75    30.00               8.00               2.00             0.00
50%    2500.50    40.00              10.00               4.00          4240.00
75%    3750.25    55.25              12.00               5.00          8890.00
max    5000.00    95.00              22.00              11.00         50570.00

In [38]:
df.describe(include='object')

       entidad   sexo tipo_localidad habla_lengua_indigena condicion_actividad afiliacion_salud
count     5000   5000           5000                  5000                5000             5000
unique      32      2              2                     2                   3                2
top     México  Mujer         Urbana                    No             Ocupada               Sí
freq       697   2591           3885                  4666                2913             4315

In [39]:
print("Tipo de dato de la salida: ", y.dtype)
print("Categorias: ", y.unique())
print()
print(pd.DataFrame({"conteo" : y.value_counts(), "porcentaje": (y.value_counts(normalize=True)*100).round(1)}))

Tipo de dato de la salida:  object
Categorias:  ['Sí' 'No']

                  conteo  porcentaje
afiliacion_salud
Sí                  4315        86.3
No                   685        13.7

In [46]:
y_num = y.map({'No': 0, 'Sí': 1})
print(y_num.dtype)
y_num.value_counts()

int64

afiliacion_salud
1    4315
0     685
Name: count, dtype: int64